#!/usr/bin/env bash
# Configures Nginx to display a custom 404 page

# Ensure Nginx is installed
apt-get update -y
apt-get install nginx -y

# Create the custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx to use the custom 404 page
sed -i '/error_page 404 \/custom_404.html;/d' /etc/nginx/sites-available/default  # Remove existing custom 404 settings if any
sed -i '/server_name _;/a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\tlocation = /custom_404.html {' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\t\troot /usr/share/nginx/html;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\t\tinternal;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \\t}' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
nginx -s reload || service nginx reload
