#!/usr/bin/env bash
# This script displays a list of currently running processes for all users,
# including those without a TTY, in a user-oriented format, showing the process hierarchy.

ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
