#!/usr/bin/env bash
# This script manages 'manage_my_process' script.

pid_file="/var/run/my_process.pid"
process_script="./manage_my_process"

start() {
    $process_script &
    echo $! > "$pid_file"
    echo "manage_my_process started"
}

stop() {
    if [ -f "$pid_file" ]; then
        kill "$(cat "$pid_file")"
        rm -f "$pid_file"
    fi
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
