#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

# Loop through all network interfaces
for interface in $(ifconfig | cut -d ' ' -f1| tr '\n' ' ')
do
	ip=$(ifconfig $interface | grep -w inet | awk '{ print $2 }')

	if [ -n "$ip" ]

	then
		echo "$ip"
	fi
done
