#!/bin/bash
# This script listens on port 98 on localhost and prints any incoming data
# Usage: sudo ./100-port_listening_on_localhost

# Create a socket using file descriptor 3
exec 3<>/dev/tcp/localhost/98

# Loop forever
while true
do
  # Read data from the socket and print it
  read -u 3 data
  echo "$data"
done
