#!/usr/bin/env bash
# This script creates an RSA key pair with a specific name, number of bits, and passphrase.

# Create the RSA key pair with the name 'school', 4096 bits, and protect it with the passphrase 'betty'.
ssh-keygen -f school -b 4096 -N betty
